import type { NextPage } from "next";
import Head from "next/head";
import { Auth, getAuth } from "firebase/auth";
const Home: NextPage = () => {
  const auth: Auth = getAuth();

  return (
    <div>
      <Head>
        <title>Next.js Firebase Jest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Next.js Firebase Jest</h1>
      </main>
    </div>
  );
};

export default Home;
